global:
  scrape_interval: 15s

scrape_configs:
  
  - job_name: "node"
    static_configs:
    - targets: ["3.22.68.65:9100/metrics"]

remote_write:
- url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
  basic_auth:
    username: 556495
    password: eyJrIjoiNzNlMTlhNzAwZjkwYTVkMzYzOGRmZjBlMWYzOGVmNWFhNWE2NjU0ZiIsIm4iOiJiZGJlamVtcGxvcHJvbWV0aGV1cyIsImlkIjo3MDI3MTl9