FROM prom/prometheus:latest
ADD ./prometheus.yml /etc/prometheus/
CMD        [ "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.local.path=/prometheus", \
             "--web.console.libraries=/etc/prometheus/console_libraries", \
             "--web.console.templates=/etc/prometheus/consoles" ]
EXPOSE 9090