---
name: Pipeline Prometheus

on:
  push:
    branches:
      - master

jobs:
  promapp:
    timeout-minutes: 15
    name: 'Prom-app'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/promapp:latest